//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace Nota_Ingreso {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class ThisDocument : Microsoft.Office.Tools.Word.DocumentBase {
        
        internal Microsoft.Office.Tools.ActionsPane ActionsPane;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbTitle;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbHosp;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lb_Fecha;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lb_Folio;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbDirH;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbDatMT;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbNomMT;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbEspMT;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbNCedMT;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbDatP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbNSSP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbNomP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbApPaP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbApMatP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbGenP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbF_Nac;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbDomP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbEscP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbEtP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbRelP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbHospProc;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbMotIng;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbObs;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbElab;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbCedElab;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl rtxtNHospital;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtFolio;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtDirH;
        
        internal Microsoft.Office.Tools.Word.DatePickerContentControl fechaElab;
        
        internal Microsoft.Office.Tools.Word.ComboBoxContentControl comboMtrat;
        
        internal Microsoft.Office.Tools.Word.ComboBoxContentControl comboCedula;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtEspe;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtNSS;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtApPat;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtApPatP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtNomP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtGenP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtFNacP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtDomP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtEscP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtEtnP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtRelP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtMotIngre;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl21;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtMedElab;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtCedElab;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl1;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl22;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl23;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        internal Microsoft.Office.Interop.Word.Application ThisApplication;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ThisDocument(global::Microsoft.Office.Tools.Word.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "ThisDocument", "ThisDocument") {
            Globals.Factory = factory;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            this.ThisApplication = this.GetHostItem<Microsoft.Office.Interop.Word.Application>(typeof(Microsoft.Office.Interop.Word.Application), "Application");
            Globals.ThisDocument = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.ActionsPane.BeginInit();
            this.lbTitle.BeginInit();
            this.lbHosp.BeginInit();
            this.lb_Fecha.BeginInit();
            this.lb_Folio.BeginInit();
            this.lbDirH.BeginInit();
            this.lbDatMT.BeginInit();
            this.lbNomMT.BeginInit();
            this.lbEspMT.BeginInit();
            this.lbNCedMT.BeginInit();
            this.lbDatP.BeginInit();
            this.lbNSSP.BeginInit();
            this.lbNomP.BeginInit();
            this.lbApPaP.BeginInit();
            this.lbApMatP.BeginInit();
            this.lbGenP.BeginInit();
            this.lbF_Nac.BeginInit();
            this.lbDomP.BeginInit();
            this.lbEscP.BeginInit();
            this.lbEtP.BeginInit();
            this.lbRelP.BeginInit();
            this.lbHospProc.BeginInit();
            this.lbMotIng.BeginInit();
            this.lbObs.BeginInit();
            this.lbElab.BeginInit();
            this.lbCedElab.BeginInit();
            this.rtxtNHospital.BeginInit();
            this.txtFolio.BeginInit();
            this.txtDirH.BeginInit();
            this.fechaElab.BeginInit();
            this.comboMtrat.BeginInit();
            this.comboCedula.BeginInit();
            this.txtEspe.BeginInit();
            this.txtNSS.BeginInit();
            this.txtApPat.BeginInit();
            this.txtApPatP.BeginInit();
            this.txtNomP.BeginInit();
            this.txtGenP.BeginInit();
            this.txtFNacP.BeginInit();
            this.txtDomP.BeginInit();
            this.txtEscP.BeginInit();
            this.txtEtnP.BeginInit();
            this.txtRelP.BeginInit();
            this.txtMotIngre.BeginInit();
            this.richTextContentControl21.BeginInit();
            this.txtMedElab.BeginInit();
            this.txtCedElab.BeginInit();
            this.richTextContentControl1.BeginInit();
            this.richTextContentControl22.BeginInit();
            this.richTextContentControl23.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.richTextContentControl23.EndInit();
            this.richTextContentControl22.EndInit();
            this.richTextContentControl1.EndInit();
            this.txtCedElab.EndInit();
            this.txtMedElab.EndInit();
            this.richTextContentControl21.EndInit();
            this.txtMotIngre.EndInit();
            this.txtRelP.EndInit();
            this.txtEtnP.EndInit();
            this.txtEscP.EndInit();
            this.txtDomP.EndInit();
            this.txtFNacP.EndInit();
            this.txtGenP.EndInit();
            this.txtNomP.EndInit();
            this.txtApPatP.EndInit();
            this.txtApPat.EndInit();
            this.txtNSS.EndInit();
            this.txtEspe.EndInit();
            this.comboCedula.EndInit();
            this.comboMtrat.EndInit();
            this.fechaElab.EndInit();
            this.txtDirH.EndInit();
            this.txtFolio.EndInit();
            this.rtxtNHospital.EndInit();
            this.lbCedElab.EndInit();
            this.lbElab.EndInit();
            this.lbObs.EndInit();
            this.lbMotIng.EndInit();
            this.lbHospProc.EndInit();
            this.lbRelP.EndInit();
            this.lbEtP.EndInit();
            this.lbEscP.EndInit();
            this.lbDomP.EndInit();
            this.lbF_Nac.EndInit();
            this.lbGenP.EndInit();
            this.lbApMatP.EndInit();
            this.lbApPaP.EndInit();
            this.lbNomP.EndInit();
            this.lbNSSP.EndInit();
            this.lbDatP.EndInit();
            this.lbNCedMT.EndInit();
            this.lbEspMT.EndInit();
            this.lbNomMT.EndInit();
            this.lbDatMT.EndInit();
            this.lbDirH.EndInit();
            this.lb_Folio.EndInit();
            this.lb_Fecha.EndInit();
            this.lbHosp.EndInit();
            this.lbTitle.EndInit();
            this.ActionsPane.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.ActionsPane = Globals.Factory.CreateActionsPane(null, null, "ActionsPane", "ActionsPane", this);
            this.lbTitle = Globals.Factory.CreateRichTextContentControl(null, null, "2336095911", "lbTitle", this);
            this.lbHosp = Globals.Factory.CreateRichTextContentControl(null, null, "1112870767", "lbHosp", this);
            this.lb_Fecha = Globals.Factory.CreateRichTextContentControl(null, null, "1007090284", "lb_Fecha", this);
            this.lb_Folio = Globals.Factory.CreateRichTextContentControl(null, null, "1670899283", "lb_Folio", this);
            this.lbDirH = Globals.Factory.CreateRichTextContentControl(null, null, "1900930751", "lbDirH", this);
            this.lbDatMT = Globals.Factory.CreateRichTextContentControl(null, null, "3966988095", "lbDatMT", this);
            this.lbNomMT = Globals.Factory.CreateRichTextContentControl(null, null, "3769097416", "lbNomMT", this);
            this.lbEspMT = Globals.Factory.CreateRichTextContentControl(null, null, "1134914462", "lbEspMT", this);
            this.lbNCedMT = Globals.Factory.CreateRichTextContentControl(null, null, "2679757862", "lbNCedMT", this);
            this.lbDatP = Globals.Factory.CreateRichTextContentControl(null, null, "2859147885", "lbDatP", this);
            this.lbNSSP = Globals.Factory.CreateRichTextContentControl(null, null, "3093418573", "lbNSSP", this);
            this.lbNomP = Globals.Factory.CreateRichTextContentControl(null, null, "2587797773", "lbNomP", this);
            this.lbApPaP = Globals.Factory.CreateRichTextContentControl(null, null, "3886047910", "lbApPaP", this);
            this.lbApMatP = Globals.Factory.CreateRichTextContentControl(null, null, "4201709322", "lbApMatP", this);
            this.lbGenP = Globals.Factory.CreateRichTextContentControl(null, null, "768122029", "lbGenP", this);
            this.lbF_Nac = Globals.Factory.CreateRichTextContentControl(null, null, "1377426226", "lbF_Nac", this);
            this.lbDomP = Globals.Factory.CreateRichTextContentControl(null, null, "1915732615", "lbDomP", this);
            this.lbEscP = Globals.Factory.CreateRichTextContentControl(null, null, "2416111015", "lbEscP", this);
            this.lbEtP = Globals.Factory.CreateRichTextContentControl(null, null, "3050172707", "lbEtP", this);
            this.lbRelP = Globals.Factory.CreateRichTextContentControl(null, null, "2850130251", "lbRelP", this);
            this.lbHospProc = Globals.Factory.CreateRichTextContentControl(null, null, "998078696", "lbHospProc", this);
            this.lbMotIng = Globals.Factory.CreateRichTextContentControl(null, null, "2570295120", "lbMotIng", this);
            this.lbObs = Globals.Factory.CreateRichTextContentControl(null, null, "3298618429", "lbObs", this);
            this.lbElab = Globals.Factory.CreateRichTextContentControl(null, null, "1189869004", "lbElab", this);
            this.lbCedElab = Globals.Factory.CreateRichTextContentControl(null, null, "2977167431", "lbCedElab", this);
            this.rtxtNHospital = Globals.Factory.CreateRichTextContentControl(null, null, "1726178585", "rtxtNHospital", this);
            this.txtFolio = Globals.Factory.CreateRichTextContentControl(null, null, "2474707464", "txtFolio", this);
            this.txtDirH = Globals.Factory.CreateRichTextContentControl(null, null, "378211563", "txtDirH", this);
            this.fechaElab = Globals.Factory.CreateDatePickerContentControl(null, null, "1001166377", "fechaElab", this);
            this.comboMtrat = Globals.Factory.CreateComboBoxContentControl(null, null, "975728911", "comboMtrat", this);
            this.comboCedula = Globals.Factory.CreateComboBoxContentControl(null, null, "2053575138", "comboCedula", this);
            this.txtEspe = Globals.Factory.CreateRichTextContentControl(null, null, "485905416", "txtEspe", this);
            this.txtNSS = Globals.Factory.CreateRichTextContentControl(null, null, "575868325", "txtNSS", this);
            this.txtApPat = Globals.Factory.CreateRichTextContentControl(null, null, "3027040718", "txtApPat", this);
            this.txtApPatP = Globals.Factory.CreateRichTextContentControl(null, null, "2411188545", "txtApPatP", this);
            this.txtNomP = Globals.Factory.CreateRichTextContentControl(null, null, "1701207138", "txtNomP", this);
            this.txtGenP = Globals.Factory.CreateRichTextContentControl(null, null, "1462076139", "txtGenP", this);
            this.txtFNacP = Globals.Factory.CreateRichTextContentControl(null, null, "2985573284", "txtFNacP", this);
            this.txtDomP = Globals.Factory.CreateRichTextContentControl(null, null, "2559662763", "txtDomP", this);
            this.txtEscP = Globals.Factory.CreateRichTextContentControl(null, null, "3347958648", "txtEscP", this);
            this.txtEtnP = Globals.Factory.CreateRichTextContentControl(null, null, "825245716", "txtEtnP", this);
            this.txtRelP = Globals.Factory.CreateRichTextContentControl(null, null, "251392476", "txtRelP", this);
            this.txtMotIngre = Globals.Factory.CreateRichTextContentControl(null, null, "2318756361", "txtMotIngre", this);
            this.richTextContentControl21 = Globals.Factory.CreateRichTextContentControl(null, null, "3527728851", "richTextContentControl21", this);
            this.txtMedElab = Globals.Factory.CreateRichTextContentControl(null, null, "1129599720", "txtMedElab", this);
            this.txtCedElab = Globals.Factory.CreateRichTextContentControl(null, null, "1935319829", "txtCedElab", this);
            this.richTextContentControl1 = Globals.Factory.CreateRichTextContentControl(null, null, "584200044", "richTextContentControl1", this);
            this.richTextContentControl22 = Globals.Factory.CreateRichTextContentControl(null, null, "1408962549", "richTextContentControl22", this);
            this.richTextContentControl23 = Globals.Factory.CreateRichTextContentControl(null, null, "1028603888", "richTextContentControl23", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // ActionsPane
            // 
            this.ActionsPane.AutoSize = false;
            this.ActionsPane.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            // 
            // lbTitle
            // 
            this.lbTitle.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbHosp
            // 
            this.lbHosp.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lb_Fecha
            // 
            this.lb_Fecha.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lb_Folio
            // 
            this.lb_Folio.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbDirH
            // 
            this.lbDirH.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbDatMT
            // 
            this.lbDatMT.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbNomMT
            // 
            this.lbNomMT.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbEspMT
            // 
            this.lbEspMT.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbNCedMT
            // 
            this.lbNCedMT.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbDatP
            // 
            this.lbDatP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbNSSP
            // 
            this.lbNSSP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbNomP
            // 
            this.lbNomP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbApPaP
            // 
            this.lbApPaP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbApMatP
            // 
            this.lbApMatP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbGenP
            // 
            this.lbGenP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbF_Nac
            // 
            this.lbF_Nac.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbDomP
            // 
            this.lbDomP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbEscP
            // 
            this.lbEscP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbEtP
            // 
            this.lbEtP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbRelP
            // 
            this.lbRelP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbHospProc
            // 
            this.lbHospProc.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbMotIng
            // 
            this.lbMotIng.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbObs
            // 
            this.lbObs.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbElab
            // 
            this.lbElab.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbCedElab
            // 
            this.lbCedElab.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // rtxtNHospital
            // 
            this.rtxtNHospital.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtFolio
            // 
            this.txtFolio.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtDirH
            // 
            this.txtDirH.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // fechaElab
            // 
            this.fechaElab.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // comboMtrat
            // 
            this.comboMtrat.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // comboCedula
            // 
            this.comboCedula.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtEspe
            // 
            this.txtEspe.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtNSS
            // 
            this.txtNSS.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtApPat
            // 
            this.txtApPat.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtApPatP
            // 
            this.txtApPatP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtNomP
            // 
            this.txtNomP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtGenP
            // 
            this.txtGenP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtFNacP
            // 
            this.txtFNacP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtDomP
            // 
            this.txtDomP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtEscP
            // 
            this.txtEscP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtEtnP
            // 
            this.txtEtnP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtRelP
            // 
            this.txtRelP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtMotIngre
            // 
            this.txtMotIngre.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl21
            // 
            this.richTextContentControl21.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtMedElab
            // 
            this.txtMedElab.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtCedElab
            // 
            this.txtCedElab.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl1
            // 
            this.richTextContentControl1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl22
            // 
            this.richTextContentControl22.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl23
            // 
            this.richTextContentControl23.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // ThisDocument
            // 
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.richTextContentControl23.Dispose();
            this.richTextContentControl22.Dispose();
            this.richTextContentControl1.Dispose();
            this.txtCedElab.Dispose();
            this.txtMedElab.Dispose();
            this.richTextContentControl21.Dispose();
            this.txtMotIngre.Dispose();
            this.txtRelP.Dispose();
            this.txtEtnP.Dispose();
            this.txtEscP.Dispose();
            this.txtDomP.Dispose();
            this.txtFNacP.Dispose();
            this.txtGenP.Dispose();
            this.txtNomP.Dispose();
            this.txtApPatP.Dispose();
            this.txtApPat.Dispose();
            this.txtNSS.Dispose();
            this.txtEspe.Dispose();
            this.comboCedula.Dispose();
            this.comboMtrat.Dispose();
            this.fechaElab.Dispose();
            this.txtDirH.Dispose();
            this.txtFolio.Dispose();
            this.rtxtNHospital.Dispose();
            this.lbCedElab.Dispose();
            this.lbElab.Dispose();
            this.lbObs.Dispose();
            this.lbMotIng.Dispose();
            this.lbHospProc.Dispose();
            this.lbRelP.Dispose();
            this.lbEtP.Dispose();
            this.lbEscP.Dispose();
            this.lbDomP.Dispose();
            this.lbF_Nac.Dispose();
            this.lbGenP.Dispose();
            this.lbApMatP.Dispose();
            this.lbApPaP.Dispose();
            this.lbNomP.Dispose();
            this.lbNSSP.Dispose();
            this.lbDatP.Dispose();
            this.lbNCedMT.Dispose();
            this.lbEspMT.Dispose();
            this.lbNomMT.Dispose();
            this.lbDatMT.Dispose();
            this.lbDirH.Dispose();
            this.lb_Folio.Dispose();
            this.lb_Fecha.Dispose();
            this.lbHosp.Dispose();
            this.lbTitle.Dispose();
            this.ActionsPane.Dispose();
            base.OnShutdown();
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
    internal sealed partial class Globals {
        
        /// 
        private Globals() {
        }
        
        private static ThisDocument _ThisDocument;
        
        private static global::Microsoft.Office.Tools.Word.Factory _factory;
        
        private static ThisRibbonCollection _ThisRibbonCollection;
        
        internal static ThisDocument ThisDocument {
            get {
                return _ThisDocument;
            }
            set {
                if ((_ThisDocument == null)) {
                    _ThisDocument = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static global::Microsoft.Office.Tools.Word.Factory Factory {
            get {
                return _factory;
            }
            set {
                if ((_factory == null)) {
                    _factory = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static ThisRibbonCollection Ribbons {
            get {
                if ((_ThisRibbonCollection == null)) {
                    _ThisRibbonCollection = new ThisRibbonCollection(_factory.GetRibbonFactory());
                }
                return _ThisRibbonCollection;
            }
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
    internal sealed partial class ThisRibbonCollection : Microsoft.Office.Tools.Ribbon.RibbonCollectionBase {
        
        /// 
        internal ThisRibbonCollection(global::Microsoft.Office.Tools.Ribbon.RibbonFactory factory) : 
                base(factory) {
        }
    }
}
