//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace Nota_Ingreso {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class ThisDocument : Microsoft.Office.Tools.Word.DocumentBase {
        
        internal Microsoft.Office.Tools.ActionsPane ActionsPane;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbTitle;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbHosp;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lb_Fecha;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lb_Folio;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbDirH;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbDatMT;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbNomMT;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbEspMT;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbNCedMT;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbDatP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbNSSP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbNomP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbApPaP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbApMatP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbGenP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbF_Nac;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbDomP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbEscP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbEtP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbRelP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbHospProc;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbMotIng;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbObs;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbElab;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbCedElab;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        internal Microsoft.Office.Interop.Word.Application ThisApplication;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ThisDocument(global::Microsoft.Office.Tools.Word.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "ThisDocument", "ThisDocument") {
            Globals.Factory = factory;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            this.ThisApplication = this.GetHostItem<Microsoft.Office.Interop.Word.Application>(typeof(Microsoft.Office.Interop.Word.Application), "Application");
            Globals.ThisDocument = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.ActionsPane.BeginInit();
            this.lbTitle.BeginInit();
            this.lbHosp.BeginInit();
            this.lb_Fecha.BeginInit();
            this.lb_Folio.BeginInit();
            this.lbDirH.BeginInit();
            this.lbDatMT.BeginInit();
            this.lbNomMT.BeginInit();
            this.lbEspMT.BeginInit();
            this.lbNCedMT.BeginInit();
            this.lbDatP.BeginInit();
            this.lbNSSP.BeginInit();
            this.lbNomP.BeginInit();
            this.lbApPaP.BeginInit();
            this.lbApMatP.BeginInit();
            this.lbGenP.BeginInit();
            this.lbF_Nac.BeginInit();
            this.lbDomP.BeginInit();
            this.lbEscP.BeginInit();
            this.lbEtP.BeginInit();
            this.lbRelP.BeginInit();
            this.lbHospProc.BeginInit();
            this.lbMotIng.BeginInit();
            this.lbObs.BeginInit();
            this.lbElab.BeginInit();
            this.lbCedElab.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.lbCedElab.EndInit();
            this.lbElab.EndInit();
            this.lbObs.EndInit();
            this.lbMotIng.EndInit();
            this.lbHospProc.EndInit();
            this.lbRelP.EndInit();
            this.lbEtP.EndInit();
            this.lbEscP.EndInit();
            this.lbDomP.EndInit();
            this.lbF_Nac.EndInit();
            this.lbGenP.EndInit();
            this.lbApMatP.EndInit();
            this.lbApPaP.EndInit();
            this.lbNomP.EndInit();
            this.lbNSSP.EndInit();
            this.lbDatP.EndInit();
            this.lbNCedMT.EndInit();
            this.lbEspMT.EndInit();
            this.lbNomMT.EndInit();
            this.lbDatMT.EndInit();
            this.lbDirH.EndInit();
            this.lb_Folio.EndInit();
            this.lb_Fecha.EndInit();
            this.lbHosp.EndInit();
            this.lbTitle.EndInit();
            this.ActionsPane.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.ActionsPane = Globals.Factory.CreateActionsPane(null, null, "ActionsPane", "ActionsPane", this);
            this.lbTitle = Globals.Factory.CreateRichTextContentControl(null, null, "2336095911", "lbTitle", this);
            this.lbHosp = Globals.Factory.CreateRichTextContentControl(null, null, "1112870767", "lbHosp", this);
            this.lb_Fecha = Globals.Factory.CreateRichTextContentControl(null, null, "1007090284", "lb_Fecha", this);
            this.lb_Folio = Globals.Factory.CreateRichTextContentControl(null, null, "1670899283", "lb_Folio", this);
            this.lbDirH = Globals.Factory.CreateRichTextContentControl(null, null, "1900930751", "lbDirH", this);
            this.lbDatMT = Globals.Factory.CreateRichTextContentControl(null, null, "3966988095", "lbDatMT", this);
            this.lbNomMT = Globals.Factory.CreateRichTextContentControl(null, null, "3769097416", "lbNomMT", this);
            this.lbEspMT = Globals.Factory.CreateRichTextContentControl(null, null, "1134914462", "lbEspMT", this);
            this.lbNCedMT = Globals.Factory.CreateRichTextContentControl(null, null, "2679757862", "lbNCedMT", this);
            this.lbDatP = Globals.Factory.CreateRichTextContentControl(null, null, "2859147885", "lbDatP", this);
            this.lbNSSP = Globals.Factory.CreateRichTextContentControl(null, null, "3093418573", "lbNSSP", this);
            this.lbNomP = Globals.Factory.CreateRichTextContentControl(null, null, "2587797773", "lbNomP", this);
            this.lbApPaP = Globals.Factory.CreateRichTextContentControl(null, null, "3886047910", "lbApPaP", this);
            this.lbApMatP = Globals.Factory.CreateRichTextContentControl(null, null, "4201709322", "lbApMatP", this);
            this.lbGenP = Globals.Factory.CreateRichTextContentControl(null, null, "768122029", "lbGenP", this);
            this.lbF_Nac = Globals.Factory.CreateRichTextContentControl(null, null, "1377426226", "lbF_Nac", this);
            this.lbDomP = Globals.Factory.CreateRichTextContentControl(null, null, "1915732615", "lbDomP", this);
            this.lbEscP = Globals.Factory.CreateRichTextContentControl(null, null, "2416111015", "lbEscP", this);
            this.lbEtP = Globals.Factory.CreateRichTextContentControl(null, null, "3050172707", "lbEtP", this);
            this.lbRelP = Globals.Factory.CreateRichTextContentControl(null, null, "2850130251", "lbRelP", this);
            this.lbHospProc = Globals.Factory.CreateRichTextContentControl(null, null, "998078696", "lbHospProc", this);
            this.lbMotIng = Globals.Factory.CreateRichTextContentControl(null, null, "2570295120", "lbMotIng", this);
            this.lbObs = Globals.Factory.CreateRichTextContentControl(null, null, "3298618429", "lbObs", this);
            this.lbElab = Globals.Factory.CreateRichTextContentControl(null, null, "1189869004", "lbElab", this);
            this.lbCedElab = Globals.Factory.CreateRichTextContentControl(null, null, "2977167431", "lbCedElab", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // ActionsPane
            // 
            this.ActionsPane.AutoSize = false;
            this.ActionsPane.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            // 
            // lbTitle
            // 
            this.lbTitle.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbHosp
            // 
            this.lbHosp.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lb_Fecha
            // 
            this.lb_Fecha.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lb_Folio
            // 
            this.lb_Folio.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbDirH
            // 
            this.lbDirH.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbDatMT
            // 
            this.lbDatMT.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbNomMT
            // 
            this.lbNomMT.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbEspMT
            // 
            this.lbEspMT.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbNCedMT
            // 
            this.lbNCedMT.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbDatP
            // 
            this.lbDatP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbNSSP
            // 
            this.lbNSSP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbNomP
            // 
            this.lbNomP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbApPaP
            // 
            this.lbApPaP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbApMatP
            // 
            this.lbApMatP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbGenP
            // 
            this.lbGenP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbF_Nac
            // 
            this.lbF_Nac.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbDomP
            // 
            this.lbDomP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbEscP
            // 
            this.lbEscP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbEtP
            // 
            this.lbEtP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbRelP
            // 
            this.lbRelP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbHospProc
            // 
            this.lbHospProc.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbMotIng
            // 
            this.lbMotIng.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbObs
            // 
            this.lbObs.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbElab
            // 
            this.lbElab.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbCedElab
            // 
            this.lbCedElab.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // ThisDocument
            // 
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.lbCedElab.Dispose();
            this.lbElab.Dispose();
            this.lbObs.Dispose();
            this.lbMotIng.Dispose();
            this.lbHospProc.Dispose();
            this.lbRelP.Dispose();
            this.lbEtP.Dispose();
            this.lbEscP.Dispose();
            this.lbDomP.Dispose();
            this.lbF_Nac.Dispose();
            this.lbGenP.Dispose();
            this.lbApMatP.Dispose();
            this.lbApPaP.Dispose();
            this.lbNomP.Dispose();
            this.lbNSSP.Dispose();
            this.lbDatP.Dispose();
            this.lbNCedMT.Dispose();
            this.lbEspMT.Dispose();
            this.lbNomMT.Dispose();
            this.lbDatMT.Dispose();
            this.lbDirH.Dispose();
            this.lb_Folio.Dispose();
            this.lb_Fecha.Dispose();
            this.lbHosp.Dispose();
            this.lbTitle.Dispose();
            this.ActionsPane.Dispose();
            base.OnShutdown();
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
    internal sealed partial class Globals {
        
        /// 
        private Globals() {
        }
        
        private static ThisDocument _ThisDocument;
        
        private static global::Microsoft.Office.Tools.Word.Factory _factory;
        
        private static ThisRibbonCollection _ThisRibbonCollection;
        
        internal static ThisDocument ThisDocument {
            get {
                return _ThisDocument;
            }
            set {
                if ((_ThisDocument == null)) {
                    _ThisDocument = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static global::Microsoft.Office.Tools.Word.Factory Factory {
            get {
                return _factory;
            }
            set {
                if ((_factory == null)) {
                    _factory = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static ThisRibbonCollection Ribbons {
            get {
                if ((_ThisRibbonCollection == null)) {
                    _ThisRibbonCollection = new ThisRibbonCollection(_factory.GetRibbonFactory());
                }
                return _ThisRibbonCollection;
            }
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
    internal sealed partial class ThisRibbonCollection : Microsoft.Office.Tools.Ribbon.RibbonCollectionBase {
        
        /// 
        internal ThisRibbonCollection(global::Microsoft.Office.Tools.Ribbon.RibbonFactory factory) : 
                base(factory) {
        }
    }
}
