//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace Nota_Ingreso {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class ThisDocument : Microsoft.Office.Tools.Word.DocumentBase {
        
        internal Microsoft.Office.Tools.ActionsPane ActionsPane;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbTitle;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbHosp;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lb_Fecha;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbDirH;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbDatMT;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbNomMT;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbEspMT;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbNCedMT;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbDatP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbNSSP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbNomP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbApPaP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbApMatP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbGenP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbF_Nac;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbDomP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbEscP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbEtP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbRelP;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbHospProc;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbMotIng;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbObs;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbElab;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl lbCedElab;
        
        public Microsoft.Office.Tools.Word.RichTextContentControl txtNHospitalNI;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtDirHNI;
        
        internal Microsoft.Office.Tools.Word.DatePickerContentControl fechaElabNI;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtEspeNI;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtNSSNI;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtApMatPNI;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtApPatPNI;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtNomPNI;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtGenPNI;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtDomPNI;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtEscPNI;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtEtnPNI;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtRelPNI;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtMotIngreNI;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtObservNI;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtMedElabNI;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtCedElabNI;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtNMTratNI;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl txtNCedMTratNI;
        
        internal Microsoft.Office.Tools.Word.DatePickerContentControl fNacPNI;
        
        internal Microsoft.Office.Tools.Word.ComboBoxContentControl cmbHosProcNI;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        internal Microsoft.Office.Interop.Word.Application ThisApplication;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ThisDocument(global::Microsoft.Office.Tools.Word.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "ThisDocument", "ThisDocument") {
            Globals.Factory = factory;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            this.ThisApplication = this.GetHostItem<Microsoft.Office.Interop.Word.Application>(typeof(Microsoft.Office.Interop.Word.Application), "Application");
            Globals.ThisDocument = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.ActionsPane.BeginInit();
            this.lbTitle.BeginInit();
            this.lbHosp.BeginInit();
            this.lb_Fecha.BeginInit();
            this.lbDirH.BeginInit();
            this.lbDatMT.BeginInit();
            this.lbNomMT.BeginInit();
            this.lbEspMT.BeginInit();
            this.lbNCedMT.BeginInit();
            this.lbDatP.BeginInit();
            this.lbNSSP.BeginInit();
            this.lbNomP.BeginInit();
            this.lbApPaP.BeginInit();
            this.lbApMatP.BeginInit();
            this.lbGenP.BeginInit();
            this.lbF_Nac.BeginInit();
            this.lbDomP.BeginInit();
            this.lbEscP.BeginInit();
            this.lbEtP.BeginInit();
            this.lbRelP.BeginInit();
            this.lbHospProc.BeginInit();
            this.lbMotIng.BeginInit();
            this.lbObs.BeginInit();
            this.lbElab.BeginInit();
            this.lbCedElab.BeginInit();
            this.txtNHospitalNI.BeginInit();
            this.txtDirHNI.BeginInit();
            this.fechaElabNI.BeginInit();
            this.txtEspeNI.BeginInit();
            this.txtNSSNI.BeginInit();
            this.txtApMatPNI.BeginInit();
            this.txtApPatPNI.BeginInit();
            this.txtNomPNI.BeginInit();
            this.txtGenPNI.BeginInit();
            this.txtDomPNI.BeginInit();
            this.txtEscPNI.BeginInit();
            this.txtEtnPNI.BeginInit();
            this.txtRelPNI.BeginInit();
            this.txtMotIngreNI.BeginInit();
            this.txtObservNI.BeginInit();
            this.txtMedElabNI.BeginInit();
            this.txtCedElabNI.BeginInit();
            this.txtNMTratNI.BeginInit();
            this.txtNCedMTratNI.BeginInit();
            this.fNacPNI.BeginInit();
            this.cmbHosProcNI.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.cmbHosProcNI.EndInit();
            this.fNacPNI.EndInit();
            this.txtNCedMTratNI.EndInit();
            this.txtNMTratNI.EndInit();
            this.txtCedElabNI.EndInit();
            this.txtMedElabNI.EndInit();
            this.txtObservNI.EndInit();
            this.txtMotIngreNI.EndInit();
            this.txtRelPNI.EndInit();
            this.txtEtnPNI.EndInit();
            this.txtEscPNI.EndInit();
            this.txtDomPNI.EndInit();
            this.txtGenPNI.EndInit();
            this.txtNomPNI.EndInit();
            this.txtApPatPNI.EndInit();
            this.txtApMatPNI.EndInit();
            this.txtNSSNI.EndInit();
            this.txtEspeNI.EndInit();
            this.fechaElabNI.EndInit();
            this.txtDirHNI.EndInit();
            this.txtNHospitalNI.EndInit();
            this.lbCedElab.EndInit();
            this.lbElab.EndInit();
            this.lbObs.EndInit();
            this.lbMotIng.EndInit();
            this.lbHospProc.EndInit();
            this.lbRelP.EndInit();
            this.lbEtP.EndInit();
            this.lbEscP.EndInit();
            this.lbDomP.EndInit();
            this.lbF_Nac.EndInit();
            this.lbGenP.EndInit();
            this.lbApMatP.EndInit();
            this.lbApPaP.EndInit();
            this.lbNomP.EndInit();
            this.lbNSSP.EndInit();
            this.lbDatP.EndInit();
            this.lbNCedMT.EndInit();
            this.lbEspMT.EndInit();
            this.lbNomMT.EndInit();
            this.lbDatMT.EndInit();
            this.lbDirH.EndInit();
            this.lb_Fecha.EndInit();
            this.lbHosp.EndInit();
            this.lbTitle.EndInit();
            this.ActionsPane.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.ActionsPane = Globals.Factory.CreateActionsPane(null, null, "ActionsPane", "ActionsPane", this);
            this.lbTitle = Globals.Factory.CreateRichTextContentControl(null, null, "2336095911", "lbTitle", this);
            this.lbHosp = Globals.Factory.CreateRichTextContentControl(null, null, "1112870767", "lbHosp", this);
            this.lb_Fecha = Globals.Factory.CreateRichTextContentControl(null, null, "1007090284", "lb_Fecha", this);
            this.lbDirH = Globals.Factory.CreateRichTextContentControl(null, null, "1900930751", "lbDirH", this);
            this.lbDatMT = Globals.Factory.CreateRichTextContentControl(null, null, "3966988095", "lbDatMT", this);
            this.lbNomMT = Globals.Factory.CreateRichTextContentControl(null, null, "3769097416", "lbNomMT", this);
            this.lbEspMT = Globals.Factory.CreateRichTextContentControl(null, null, "1134914462", "lbEspMT", this);
            this.lbNCedMT = Globals.Factory.CreateRichTextContentControl(null, null, "2679757862", "lbNCedMT", this);
            this.lbDatP = Globals.Factory.CreateRichTextContentControl(null, null, "2859147885", "lbDatP", this);
            this.lbNSSP = Globals.Factory.CreateRichTextContentControl(null, null, "3093418573", "lbNSSP", this);
            this.lbNomP = Globals.Factory.CreateRichTextContentControl(null, null, "2587797773", "lbNomP", this);
            this.lbApPaP = Globals.Factory.CreateRichTextContentControl(null, null, "3886047910", "lbApPaP", this);
            this.lbApMatP = Globals.Factory.CreateRichTextContentControl(null, null, "4201709322", "lbApMatP", this);
            this.lbGenP = Globals.Factory.CreateRichTextContentControl(null, null, "768122029", "lbGenP", this);
            this.lbF_Nac = Globals.Factory.CreateRichTextContentControl(null, null, "1377426226", "lbF_Nac", this);
            this.lbDomP = Globals.Factory.CreateRichTextContentControl(null, null, "1915732615", "lbDomP", this);
            this.lbEscP = Globals.Factory.CreateRichTextContentControl(null, null, "2416111015", "lbEscP", this);
            this.lbEtP = Globals.Factory.CreateRichTextContentControl(null, null, "3050172707", "lbEtP", this);
            this.lbRelP = Globals.Factory.CreateRichTextContentControl(null, null, "2850130251", "lbRelP", this);
            this.lbHospProc = Globals.Factory.CreateRichTextContentControl(null, null, "998078696", "lbHospProc", this);
            this.lbMotIng = Globals.Factory.CreateRichTextContentControl(null, null, "2570295120", "lbMotIng", this);
            this.lbObs = Globals.Factory.CreateRichTextContentControl(null, null, "3298618429", "lbObs", this);
            this.lbElab = Globals.Factory.CreateRichTextContentControl(null, null, "1189869004", "lbElab", this);
            this.lbCedElab = Globals.Factory.CreateRichTextContentControl(null, null, "2977167431", "lbCedElab", this);
            this.txtNHospitalNI = Globals.Factory.CreateRichTextContentControl(null, null, "1726178585", "txtNHospitalNI", this);
            this.txtDirHNI = Globals.Factory.CreateRichTextContentControl(null, null, "378211563", "txtDirHNI", this);
            this.fechaElabNI = Globals.Factory.CreateDatePickerContentControl(null, null, "1001166377", "fechaElabNI", this);
            this.txtEspeNI = Globals.Factory.CreateRichTextContentControl(null, null, "485905416", "txtEspeNI", this);
            this.txtNSSNI = Globals.Factory.CreateRichTextContentControl(null, null, "575868325", "txtNSSNI", this);
            this.txtApMatPNI = Globals.Factory.CreateRichTextContentControl(null, null, "3027040718", "txtApMatPNI", this);
            this.txtApPatPNI = Globals.Factory.CreateRichTextContentControl(null, null, "2411188545", "txtApPatPNI", this);
            this.txtNomPNI = Globals.Factory.CreateRichTextContentControl(null, null, "1701207138", "txtNomPNI", this);
            this.txtGenPNI = Globals.Factory.CreateRichTextContentControl(null, null, "1462076139", "txtGenPNI", this);
            this.txtDomPNI = Globals.Factory.CreateRichTextContentControl(null, null, "2559662763", "txtDomPNI", this);
            this.txtEscPNI = Globals.Factory.CreateRichTextContentControl(null, null, "3347958648", "txtEscPNI", this);
            this.txtEtnPNI = Globals.Factory.CreateRichTextContentControl(null, null, "825245716", "txtEtnPNI", this);
            this.txtRelPNI = Globals.Factory.CreateRichTextContentControl(null, null, "251392476", "txtRelPNI", this);
            this.txtMotIngreNI = Globals.Factory.CreateRichTextContentControl(null, null, "2318756361", "txtMotIngreNI", this);
            this.txtObservNI = Globals.Factory.CreateRichTextContentControl(null, null, "3527728851", "txtObservNI", this);
            this.txtMedElabNI = Globals.Factory.CreateRichTextContentControl(null, null, "1129599720", "txtMedElabNI", this);
            this.txtCedElabNI = Globals.Factory.CreateRichTextContentControl(null, null, "1935319829", "txtCedElabNI", this);
            this.txtNMTratNI = Globals.Factory.CreateRichTextContentControl(null, null, "1372887101", "txtNMTratNI", this);
            this.txtNCedMTratNI = Globals.Factory.CreateRichTextContentControl(null, null, "3321671902", "txtNCedMTratNI", this);
            this.fNacPNI = Globals.Factory.CreateDatePickerContentControl(null, null, "2900150605", "fNacPNI", this);
            this.cmbHosProcNI = Globals.Factory.CreateComboBoxContentControl(null, null, "635688600", "cmbHosProcNI", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // ActionsPane
            // 
            this.ActionsPane.AutoSize = false;
            this.ActionsPane.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            // 
            // lbTitle
            // 
            this.lbTitle.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbHosp
            // 
            this.lbHosp.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lb_Fecha
            // 
            this.lb_Fecha.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbDirH
            // 
            this.lbDirH.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbDatMT
            // 
            this.lbDatMT.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbNomMT
            // 
            this.lbNomMT.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbEspMT
            // 
            this.lbEspMT.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbNCedMT
            // 
            this.lbNCedMT.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbDatP
            // 
            this.lbDatP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbNSSP
            // 
            this.lbNSSP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbNomP
            // 
            this.lbNomP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbApPaP
            // 
            this.lbApPaP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbApMatP
            // 
            this.lbApMatP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbGenP
            // 
            this.lbGenP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbF_Nac
            // 
            this.lbF_Nac.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbDomP
            // 
            this.lbDomP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbEscP
            // 
            this.lbEscP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbEtP
            // 
            this.lbEtP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbRelP
            // 
            this.lbRelP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbHospProc
            // 
            this.lbHospProc.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbMotIng
            // 
            this.lbMotIng.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbObs
            // 
            this.lbObs.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbElab
            // 
            this.lbElab.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lbCedElab
            // 
            this.lbCedElab.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtNHospitalNI
            // 
            this.txtNHospitalNI.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtDirHNI
            // 
            this.txtDirHNI.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // fechaElabNI
            // 
            this.fechaElabNI.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtEspeNI
            // 
            this.txtEspeNI.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtNSSNI
            // 
            this.txtNSSNI.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtApMatPNI
            // 
            this.txtApMatPNI.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtApPatPNI
            // 
            this.txtApPatPNI.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtNomPNI
            // 
            this.txtNomPNI.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtGenPNI
            // 
            this.txtGenPNI.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtDomPNI
            // 
            this.txtDomPNI.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtEscPNI
            // 
            this.txtEscPNI.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtEtnPNI
            // 
            this.txtEtnPNI.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtRelPNI
            // 
            this.txtRelPNI.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtMotIngreNI
            // 
            this.txtMotIngreNI.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtObservNI
            // 
            this.txtObservNI.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtMedElabNI
            // 
            this.txtMedElabNI.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtCedElabNI
            // 
            this.txtCedElabNI.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtNMTratNI
            // 
            this.txtNMTratNI.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // txtNCedMTratNI
            // 
            this.txtNCedMTratNI.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // fNacPNI
            // 
            this.fNacPNI.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // cmbHosProcNI
            // 
            this.cmbHosProcNI.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // ThisDocument
            // 
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.cmbHosProcNI.Dispose();
            this.fNacPNI.Dispose();
            this.txtNCedMTratNI.Dispose();
            this.txtNMTratNI.Dispose();
            this.txtCedElabNI.Dispose();
            this.txtMedElabNI.Dispose();
            this.txtObservNI.Dispose();
            this.txtMotIngreNI.Dispose();
            this.txtRelPNI.Dispose();
            this.txtEtnPNI.Dispose();
            this.txtEscPNI.Dispose();
            this.txtDomPNI.Dispose();
            this.txtGenPNI.Dispose();
            this.txtNomPNI.Dispose();
            this.txtApPatPNI.Dispose();
            this.txtApMatPNI.Dispose();
            this.txtNSSNI.Dispose();
            this.txtEspeNI.Dispose();
            this.fechaElabNI.Dispose();
            this.txtDirHNI.Dispose();
            this.txtNHospitalNI.Dispose();
            this.lbCedElab.Dispose();
            this.lbElab.Dispose();
            this.lbObs.Dispose();
            this.lbMotIng.Dispose();
            this.lbHospProc.Dispose();
            this.lbRelP.Dispose();
            this.lbEtP.Dispose();
            this.lbEscP.Dispose();
            this.lbDomP.Dispose();
            this.lbF_Nac.Dispose();
            this.lbGenP.Dispose();
            this.lbApMatP.Dispose();
            this.lbApPaP.Dispose();
            this.lbNomP.Dispose();
            this.lbNSSP.Dispose();
            this.lbDatP.Dispose();
            this.lbNCedMT.Dispose();
            this.lbEspMT.Dispose();
            this.lbNomMT.Dispose();
            this.lbDatMT.Dispose();
            this.lbDirH.Dispose();
            this.lb_Fecha.Dispose();
            this.lbHosp.Dispose();
            this.lbTitle.Dispose();
            this.ActionsPane.Dispose();
            base.OnShutdown();
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
    internal sealed partial class Globals {
        
        /// 
        private Globals() {
        }
        
        private static ThisDocument _ThisDocument;
        
        private static global::Microsoft.Office.Tools.Word.Factory _factory;
        
        private static ThisRibbonCollection _ThisRibbonCollection;
        
        internal static ThisDocument ThisDocument {
            get {
                return _ThisDocument;
            }
            set {
                if ((_ThisDocument == null)) {
                    _ThisDocument = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static global::Microsoft.Office.Tools.Word.Factory Factory {
            get {
                return _factory;
            }
            set {
                if ((_factory == null)) {
                    _factory = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static ThisRibbonCollection Ribbons {
            get {
                if ((_ThisRibbonCollection == null)) {
                    _ThisRibbonCollection = new ThisRibbonCollection(_factory.GetRibbonFactory());
                }
                return _ThisRibbonCollection;
            }
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
    internal sealed partial class ThisRibbonCollection : Microsoft.Office.Tools.Ribbon.RibbonCollectionBase {
        
        /// 
        internal ThisRibbonCollection(global::Microsoft.Office.Tools.Ribbon.RibbonFactory factory) : 
                base(factory) {
        }
    }
}
